language: python
python:
    - "2.7"
    - "3.6"
before_script:
    - flake8 .
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer
    - sudo update-java-alternatives -s java-8-oracle

script:
    - python scripts/ttl2others.py trellis.ttl
    - html5validator

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: ns
  upload-dir: ns
  default_text_charset: 'utf-8'
