language: python
python:
    - "2.7"
    - "3.4"
before_script:
    - flake8 .
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer
    - sudo update-java-alternatives -s java-8-oracle

install:
    - pip install html5validator

script:
    - python scripts/ttl2others.py trellis.ttl
