language: python

cache: pip

branches:
  only:
    - main

stages:
  - test
  - deploy

jobs:
  include:
    # Test with Python 2
    - name: "Python 2"
      stage: test
      python: 2.7
      before_script:
        - flake8 .
        - sudo apt-get update
        - sudo apt-get install default-jdk
      script:
        - python scripts/ttl2others.py trellis.ttl
        - html5validator

    # Test with Python 3
    - name: "Python 3"
      stage: test
      python: 3.6
      before_script:
        - flake8 .
        - sudo apt-get update
        - sudo apt-get install default-jdk
      script:
        - python3 scripts/ttl2others.py trellis.ttl
        - html5validator

    # AWS deployment
    - name: "Deploy to AWS"
      stage: deploy
      python: 3.6
      script: python3 scripts/ttl2others.py trellis.ttl
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: $AWS_BUCKET
        skip_cleanup: true
        local_dir: ns
        upload_dir: ns
        default_text_charset: 'utf-8'
